export const events = [
  {
    id: 1,
    badge: "Seminar",
    title: "Understanding Pelvic Health",
    description:
      "Learn about pelvic floor disorders and physiotherapy solutions.",
    date: "2025-07-13",
    time: "10:00 AM - 2:00 PM",
    location: "Lagos, Nigeria",
    link: "/events/1",
  },
  {
    id: 2,
    badge: "Panel Session",
    title: "Women's Health: Voices from the Field",
    description: "A panel discussion with experts and advocates.",
    date: "2025-07-25",
    time: "11:00 AM - 3:00 PM",
    location: "Online / Lagos",
    link: "/events/2",
  },
  {
    id: 3,
    badge: "Skills Training",
    title: "Physiotherapy Skills Workshop",
    description: "Hands-on training for students and professionals.",
    date: "2025-08-10",
    time: "9:00 AM - 4:00 PM",
    location: "Abuja, Nigeria",
    link: "/events/3",
  },
  {
    id: 4,
    badge: "Outreach",
    title: "Community Outreach in Ikeja",
    description: "Free health screening and education.",
    date: "2025-08-22",
    time: "7:00 AM - 11:00 AM",
    location: "Ikeja, Lagos",
    link: "/events/4",
  },
];
